use_frameworks!

platform :ios, '9.0'

target 'SNCountryChooseKit_Example' do
  pod 'SNCountryChooseKit', :path => '../'

  target 'SNCountryChooseKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
