source 'https://github.com/CocoaPods/Specs.git'
# 私有库
source 'https://github.com/keroushe/KHSpecs.git'
use_frameworks!

platform :ios, '9.0'

target 'SNCountryChooseKit_Example' do
  pod 'SNCountryChooseKit', :path => '../'

  target 'SNCountryChooseKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
